// This file is generated by Slice Machine. Update with care!

import Main from './Main';
import Test from './Test';

export {
	Main,
	Test,
};

export const components = {
	main: Main,
	test: Test,
};
